# Contains dependencies without specific verions
# run: conda env create -f environment.yml
name: rl
dependencies:
- matplotlib
- numpy
- python=3
- pyyaml
- pip:
  - gym
  - tensorflow
  - stable-baselines
